import pyautogui as pg
num1 = input('Введите цифру от 1 до 8:')
pg.hotkey('ctrl', 'alt', 'g')
pg.hotkey('ctrl', 't')
pg.hotkey('ctrl', 't')
pg.hotkey('ctrl', 't')
pg.hotkey('ctrl', 't')
pg.hotkey('ctrl', 't')
pg.hotkey('ctrl', 't')
pg.hotkey('ctrl', 't')
pg.hotkey('ctrl', 't')
pg.hotkey('ctrl', 't')
pg.hotkey('ctrl', 't')
pg.hotkey('ctrl', num1)
